import { useEffect, useState, type ComponentProps } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { api, esp32, tokenStore } from './api/apiClient';
import { Button, Card, StatusPill } from './components/ui';
import type { Device, DeviceSettings, Progress, ScreenName } from './types';

const screens: ScreenName[] = ['Dashboard', 'ConnectDevice', 'Calibration', 'LivePosture', 'DailyProgress', 'MonthlyProgress', 'DeviceSettings', 'HowToUse'];

export default function App() {
  const [screen, setScreen] = useState<ScreenName>('Login');
  const [token, setToken] = useState<string | null>(null);
  const [activeDevice, setActiveDevice] = useState<Device | null>(null);

  useEffect(() => { tokenStore.get().then((saved: string | null) => { if (saved) { setToken(saved); setScreen('Dashboard'); } }); }, []);

  const signOut = async () => { await tokenStore.clear(); setToken(null); setActiveDevice(null); setScreen('Login'); };

  return <SafeAreaView style={styles.safe}><StatusBar style="dark" /><ScrollView contentContainerStyle={styles.container}>
    <Text style={styles.logo}>Alino</Text><Text style={styles.subtitle}>Simple posture coaching for every day.</Text>
    {token && <View style={styles.nav}>{screens.map((item) => <Text key={item} onPress={() => setScreen(item)} style={[styles.navItem, screen === item && styles.navActive]}>{item.replace(/([A-Z])/g, ' $1').trim()}</Text>)}</View>}
    {screen === 'Login' && <Auth mode="login" onSwitch={() => setScreen('Register')} onAuthed={async (newToken) => { await tokenStore.set(newToken); setToken(newToken); setScreen('Dashboard'); }} />}
    {screen === 'Register' && <Auth mode="register" onSwitch={() => setScreen('Login')} onAuthed={async (newToken) => { await tokenStore.set(newToken); setToken(newToken); setScreen('Dashboard'); }} />}
    {screen === 'Dashboard' && <Dashboard activeDevice={activeDevice} onSignOut={signOut} />}
    {screen === 'ConnectDevice' && <ConnectDevice onConnected={setActiveDevice} />}
    {screen === 'Calibration' && <Calibration activeDevice={activeDevice} />}
    {screen === 'LivePosture' && <LivePosture activeDevice={activeDevice} />}
    {screen === 'DailyProgress' && <ProgressScreen type="daily" activeDevice={activeDevice} />}
    {screen === 'MonthlyProgress' && <ProgressScreen type="monthly" activeDevice={activeDevice} />}
    {screen === 'DeviceSettings' && <Settings activeDevice={activeDevice} />}
    {screen === 'HowToUse' && <HowToUse />}
  </ScrollView></SafeAreaView>;
}

function Auth({ mode, onSwitch, onAuthed }: { mode: 'login' | 'register'; onSwitch: () => void; onAuthed: (token: string) => void }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async () => { try { setLoading(true); const res = mode === 'login' ? await api.login({ email, password }) : await api.register({ name, email, password }); onAuthed(res.token); } catch (e) { Alert.alert('Authentication failed', e instanceof Error ? e.message : 'Please try again.'); } finally { setLoading(false); } };
  return <Card><Text style={styles.title}>{mode === 'login' ? 'Welcome back' : 'Create your account'}</Text>{mode === 'register' && <Input placeholder="Name" value={name} onChangeText={setName} />}<Input placeholder="Email" value={email} onChangeText={setEmail} /><Input placeholder="Password" value={password} onChangeText={setPassword} secureTextEntry /><Button title={loading ? 'Please wait...' : mode === 'login' ? 'Log in' : 'Register'} onPress={submit} disabled={loading} /><Text onPress={onSwitch} style={styles.link}>{mode === 'login' ? 'Need an account? Register' : 'Already have an account? Log in'}</Text></Card>;
}
function Input(props: ComponentProps<typeof TextInput>) { return <TextInput {...props} style={styles.input} placeholderTextColor="#718096" autoCapitalize="none" />; }
function Dashboard({ activeDevice, onSignOut }: { activeDevice: Device | null; onSignOut: () => void }) { return <><Card><Text style={styles.title}>Dashboard</Text><StatusPill tone={activeDevice ? 'good' : 'unknown'} label={activeDevice ? `Connected: ${activeDevice.deviceName}` : 'No device connected'} /></Card><Metric title="Posture Score" value="--" /><Metric title="Latest Angle" value="Waiting for data" /><Metric title="Alerts" value="No recent alerts" /><Metric title="Daily Progress" value="Open Daily Progress" /><Metric title="Monthly Progress" value="Open Monthly Progress" /><Button title="Sign out" onPress={onSignOut} /></>; }
function Metric({ title, value }: { title: string; value: string }) { return <Card><Text style={styles.metric}>{title}</Text><Text style={styles.value}>{value}</Text></Card>; }
function ConnectDevice({ onConnected }: { onConnected: (device: Device) => void }) { const [loading, setLoading] = useState(false); const connect = async () => { try { setLoading(true); const info = await esp32.getDeviceInfo(); const device = await api.createDevice({ deviceName: info.deviceName, deviceUid: info.deviceUid, deviceIp: '192.168.4.1' }); onConnected(device); Alert.alert('Device connected', `${info.deviceName} is ready.`); } catch (e) { Alert.alert('Could not connect', e instanceof Error ? e.message : 'Make sure your phone is on the Alino Wi-Fi.'); } finally { setLoading(false); } }; return <Card><Text style={styles.title}>Connect Device</Text><Text style={styles.body}>Turn on your Alino device and connect your phone to its Wi-Fi network. Then tap the button below.</Text><Button title={loading ? 'Connecting...' : 'Connect Device'} onPress={connect} disabled={loading} /></Card>; }
function Calibration({ activeDevice }: { activeDevice: Device | null }) { const [loading, setLoading] = useState(false); const run = async () => { if (!activeDevice) return; try { setLoading(true); const result = await esp32.calibrate(); await api.createCalibration({ deviceId: activeDevice.id, baselineAngle: result.baselineAngle, thresholdAngle: result.thresholdAngle }); Alert.alert('Calibration complete', result.message); } catch (e) { Alert.alert('Calibration failed', e instanceof Error ? e.message : 'Please try again.'); } finally { setLoading(false); } }; return <Card><Text style={styles.title}>Calibration</Text>{['Clip the device correctly.', 'Sit in your correct posture.', 'Stay still.', 'Tap Calibrate.'].map((step, i) => <Text key={step} style={styles.body}>{i + 1}. {step}</Text>)}<Button title={loading ? 'Calibrating...' : 'Calibrate'} onPress={run} disabled={!activeDevice || loading} /></Card>; }
function LivePosture({ activeDevice }: { activeDevice: Device | null }) { const [angle, setAngle] = useState<number | null>(null); const tone = angle == null ? 'unknown' : angle <= 12 ? 'good' : angle <= 18 ? 'warning' : 'bad'; return <Card><Text style={styles.title}>Live Posture</Text><StatusPill tone={tone} label={angle == null ? 'No data yet' : tone === 'good' ? 'Good posture' : 'Adjust posture'} /><Text style={styles.big}>{angle == null ? '--' : `${angle.toFixed(1)}°`}</Text><Button title="Refresh latest reading" onPress={async () => { if (!activeDevice) return; const reading = await api.latestReading(activeDevice.id) as { angle?: number }; setAngle(reading.angle ?? null); }} disabled={!activeDevice} /></Card>; }
function ProgressScreen({ type, activeDevice }: { type: 'daily' | 'monthly'; activeDevice: Device | null }) { const [progress, setProgress] = useState<Progress>({}); const label = type === 'daily' ? new Date().toISOString().slice(0, 10) : new Date().toISOString().slice(0, 7); return <Card><Text style={styles.title}>{type === 'daily' ? 'Daily' : 'Monthly'} Progress</Text><Button title="Load progress" onPress={async () => { if (!activeDevice) return; setProgress(type === 'daily' ? await api.dailyProgress(activeDevice.id, label) : await api.monthlyProgress(activeDevice.id, label)); }} disabled={!activeDevice} /><Text style={styles.value}>Score: {progress.postureScore ?? '--'}</Text><Text style={styles.body}>Good minutes: {progress.goodPostureMinutes ?? '--'}</Text><Text style={styles.body}>Wrong minutes: {progress.wrongPostureMinutes ?? '--'}</Text><Text style={styles.body}>Alerts: {progress.alertCount ?? '--'}</Text></Card>; }
function Settings({ activeDevice }: { activeDevice: Device | null }) { const [settings, setSettings] = useState<DeviceSettings>({ deviceId: activeDevice?.id ?? '', alertEnabled: true, vibrationEnabled: true, thresholdAngle: 12 }); useEffect(() => { if (activeDevice) setSettings((s: DeviceSettings) => ({ ...s, deviceId: activeDevice.id })); }, [activeDevice]); return <Card><Text style={styles.title}>Device Settings</Text><Row label="Posture alerts" value={settings.alertEnabled} onValueChange={(alertEnabled) => setSettings({ ...settings, alertEnabled })} /><Row label="Vibration" value={settings.vibrationEnabled} onValueChange={(vibrationEnabled) => setSettings({ ...settings, vibrationEnabled })} /><Input keyboardType="numeric" value={String(settings.thresholdAngle)} onChangeText={(v: string) => setSettings({ ...settings, thresholdAngle: Number(v) || 0 })} /><Button title="Save settings" onPress={async () => { if (activeDevice) await api.updateSettings(activeDevice.id, settings); }} disabled={!activeDevice} /></Card>; }
function Row({ label, value, onValueChange }: { label: string; value: boolean; onValueChange: (v: boolean) => void }) { return <View style={styles.row}><Text style={styles.body}>{label}</Text><Switch value={value} onValueChange={onValueChange} /></View>; }
function HowToUse() { return <Card><Text style={styles.title}>How to Use Alino</Text>{['Charge and turn on the device.', 'Connect your phone to the Alino Wi-Fi.', 'Use Connect Device once per device.', 'Calibrate while sitting correctly.', 'Check Live Posture and Progress regularly.'].map((item) => <Text key={item} style={styles.body}>• {item}</Text>)}</Card>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F4F8FB' }, container: { padding: 20, paddingBottom: 44 }, logo: { fontSize: 38, fontWeight: '800', color: '#176B87' }, subtitle: { color: '#52616B', marginBottom: 16 }, nav: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 }, navItem: { backgroundColor: '#E6F4F1', color: '#176B87', padding: 9, borderRadius: 999, overflow: 'hidden' }, navActive: { backgroundColor: '#176B87', color: '#fff' }, title: { fontSize: 22, fontWeight: '800', color: '#102A43', marginBottom: 12 }, body: { fontSize: 16, color: '#334E68', marginBottom: 8, lineHeight: 23 }, input: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 12, padding: 14, marginBottom: 10, fontSize: 16 }, link: { textAlign: 'center', color: '#176B87', marginTop: 16, fontWeight: '700' }, metric: { color: '#64748B', fontWeight: '700' }, value: { color: '#102A43', fontSize: 20, fontWeight: '800', marginTop: 6 }, big: { fontSize: 56, fontWeight: '900', color: '#102A43', marginVertical: 18 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' } });
